export const API_STATUS = {
  OK: 200,
  CREATED_SUCCESSFULLY: 201,
  DELETED_SUCCESSFULLY: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,

  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export const MESSAGE_CODE = {
  OK: "OK",
  CREATED_SUCCESSFULLY: "CREATED_SUCCESSFULLY",
  DELETED_SUCCESSFULLY: "DELETED_SUCCESSFULLY",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
